# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae539590ab8080a3c387a0923ba934a845d6a7a00d7de9d9b1228aada18f36ebe9c35a0fa0114f26b4d989d28ea903d4b03f59b3814c0a369d21279a1d2907ff

test:
  secret_key_base: 0a6d229f9aa0f54435206c21f94e0460b89d73581b636f58cd6f4f696fb0d16a45f815f73eac7535d234b30bcb78948d2fad787f010195d4417f725d08832c9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
